language: node_js
node_js:
- 10.5.0
before_deploy:
- npm run build
deploy:
  provider: npm
  email: jirat@rentspree.com
  on:
    tags: true
  api_key:
    secure: WVGKBUcO7rKnZzuk02U8eQLXs81Kgumrt72mGch6CazJ4pUOtc1p6BgbV9KKFPwxyZzoYSplk2AyeOe0ihLX4h4Ml3mCjf70IOCMHNrDM/6MIkdgH76nvAuU+ntNfDU3usqErwePSUuTY1+8E2PNEh+bNNo+z8lyGcO2GFCiZAYl5BSKMh9dzvWr1q4sr+EUm+cRuU6IIgzQJ/jJPJbnBIRbwryeFL2/tGwxZYupqL47ydVkfqxGS3t74rfNeZs6sMwYVKtKBhWtp7VxBlqc6wJP0V1YciD7LBJ+2wrktB2f6L+ueYtVBgxPGet+VVEwIGVps0pE1fkq2ujSytvDPXBbTtEE539F3eY7VxJYgFsaPbbggxKwWHE28sge8JoMBKj7mQYFIZSE7VnyegttuByhf1HS/4sJzwNAFSj8c7ismbVYXrQuc0UL73AbbzLvYgLDWiJZXq3xRGRvqXQhOeIBXyeFgKHoeJCx/CLI8Sj7ouIDLmwiDQ91XyrwdVbIbY1cNCPxgQIb491DWY2q72rNDqHGpM+kj5q9ZHhQJKfxcJ6r4hk9Axb3sg5EENhat9CVsektpLS+soEhiZJD6Zyq8waUbgtWiXZ0pGxdyesJDRcr/fXfUXztqogcP2hdODzHOeHv/b0kylVVLX3QQjblBoocN2JmiPxoLjjqdug=
